package com.ust.retail.store.pim.dto.purchaseorder.operation;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.ust.retail.store.pim.common.annotations.OnCreate;
import com.ust.retail.store.pim.common.annotations.OnUpdate;
import com.ust.retail.store.pim.common.bases.BaseDTO;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@AllArgsConstructor
@Getter
public class PurchaseOrderAddProductRequestDTO extends BaseDTO {
	@Null(message = "Purchase Order ID should not be present when creating.", groups = OnCreate.class)
	@NotNull(message = "Purchase Order ID is mandatory when updating.", groups = OnUpdate.class)
	private Long purchaseOrderId;

	@NotNull(message = "Vendor Master ID is mandatory when creating.", groups = OnCreate.class)
	private Long vendorMasterId;

	@NotNull(message = "Store Number ID is mandatory when creating.", groups = OnCreate.class)
	private Long storeNumId;

	@NotNull(message = "UPC Master ID is mandatory.", groups = {OnCreate.class, OnUpdate.class})
	private Long upcMasterId;

	@NotNull(message = "# Cases is mandatory.", groups = {OnCreate.class, OnUpdate.class})
	private Integer caseNum;

	@NotNull(message = "# Pallets is mandatory.", groups = {OnCreate.class, OnUpdate.class})
	private Integer palletNum;

	@NotNull(message = "Total Qty is mandatory.", groups = {OnCreate.class, OnUpdate.class})
	private Integer totalAmount;

	@JsonIgnore
	private boolean autogenerated;

}
